import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "../../auth";
import toast, { Toaster } from "react-hot-toast";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body
          className={
            (clsx("inset-0 min-h-screen bg-background font-sans antialiased"),
            inter.className)
          }
        >
          <main className="mx-auto flex-grow">{children}</main>
        </body>
      </html>
    </SessionProvider>
  );
}
